status:
    path: /v1/status
    controller: App\Controller\StatusController::status
    methods: GET

player-list:
    path: /v1/players
    controller: App\Controller\Player\PlayerListController
    methods: GET